ckanext/datavic_odp_theme/views/sitemap.py
import logging

from flask import Blueprint, make_response

import ckan.model as model
import ckan.plugins.toolkit as tk


log = logging.getLogger(__name__)
odp_sitemap = Blueprint("sitemap", __name__)


@odp_sitemap.route("/sitemap.xml")
@odp_sitemap.route("/sitemap")
def index():
    sitemap_data = '<?xml version="1.0" encoding="UTF-8"?>\n'
    sitemap_data += '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n'
    host_url: str = tk.request.host_url.replace("http:", "https:").strip("/")

    for package in _get_packages():
        modified_at: str = package.metadata_modified.strftime("%Y-%m-%d")
        sitemap_data += (
            f"<url><loc>{host_url}/dataset/{package.name}</loc>"
            f"<lastmod>{modified_at}</lastmod></url>\n"
        )

    for organisation in model.Group.all("organization"):
        sitemap_data += (
            f"<url><loc>{host_url}/organization/{organisation.name}</loc></url>\n"
        )

    for group in model.Group.all("group"):
        sitemap_data += f"<url><loc>{host_url}/group/{group.name}</loc></url>\n"

    sitemap_data += "</urlset>"
    response = make_response(sitemap_data)
    response.headers["Content-Type"] = "application/xml"

    return response


def _get_packages():
    package = model.Package

    return (
        model.Session.query(package.name, package.metadata_modified)
        .filter(package.state == model.State.ACTIVE)
        .filter(package.private == False)
        .order_by(package.name)
        .all()
    )

ckanext/datavic_odp_theme/templates/base.html
{% ckan_extends %}

{% block htmltag %}

  {% set lang = h.lang() %}

  {% if lang == 'en_AU' %}
    {% set lang = 'en-au' %}
  {% endif %}

  <!--[if IE 9]> <html lang="en-au" class="ie9"> <![endif]-->
  <!--[if gt IE 8]><!--> <html lang="{{ lang }}"> <!--<![endif]-->
{% endblock %}

{% block head_extras %}
  {{ super() }}

  {% if h.get_gtm_container_id() %}
    {% snippet "snippets/gtm_include.html" %}
  {% endif %}

  {% if h.hotjar_tracking_enabled() %}
    {% snippet "snippets/hotjar.html" %}
  {% endif %}

  {% if h.monsido_tracking_enabled() %}
    {% snippet "snippets/monsido.html" %}
  {% endif %}

  {% if h.get_google_optimize_id() %}
    {% snippet "snippets/google_optimize.html" %}
  {% endif %}
{% endblock %}

{% block styles %}
  {{ super() }}
  {% asset 'datavic_odp_theme/datavic_odp_theme-css' %}
{% endblock %}

{% block scripts %}
  {{ super() }}
  {% asset 'datavic_odp_theme/datavic_odp_theme-js' %}
{% endblock %}

ckanext/datavic_odp_theme/templates/footer.html
<footer>
  <div class="rpl-site-footer">
    <div class="rpl-site-footer__main">
      <ul class="rpl-footer-nav">
        <li class="rpl-footer-nav__menu-item rpl-footer-nav__menu-item--parent">
          <h2 class="rpl-footer-nav__heading">
            <a href="{{ h.url_for('search') }}" class="rpl-link rpl-menu__item-link">{{ _('Data') }}</a>
          </h2>
        </li>
        <li class="rpl-footer-nav__menu-item rpl-footer-nav__menu-item--parent">
          <h2 class="rpl-footer-nav__heading">
            <a href="{{ h.get_parent_site_url() }}/about-datavic" class="rpl-link rpl-menu__item-link">{{ _('About DataVic') }}</a>
          </h2>
        </li>
        <li class="rpl-footer-nav__menu-item rpl-footer-nav__menu-item--parent">
          <h2 class="rpl-footer-nav__heading">
            <a href="{{ h.get_parent_site_url() }}/contact-us" class="rpl-link rpl-menu__item-link">{{ _('Contact us') }}</a>
          </h2>
        </li>
      </ul>
      <div class="rpl-acknowledgement rpl-site-footer__acknowledgement">
        <img class="rpl-acknowledgement__flag" src="/images/aboriginal-flag.png" alt="Aboriginal flag" />
        <img class="rpl-acknowledgement__flag" src="/images/torres-strait-islander-flag.png" alt="Torres Strait Islander flag" />
        <div class="rpl-acknowledgement__text">{{ _('The Victorian Government acknowledges Aboriginal Traditional Owners of Country throughout Victoria and pays respect to their cultures and Elders past, present and emerging.') }}</div>
      </div>
    </div>
    <div class="rpl-site-footer__bottom">
      <div class="rpl-site-footer__bottom-main">
        <div class="rpl-links-and-copyright">
          <ul class="rpl-links-and-copyright__links"><!-- {# The comments here are intentional - to remove whitespace between inline block elements #}
            --><li><a href="{{ h.get_parent_site_url() }}/privacy-vicgovau">{{ _('Privacy') }}</a></li><!--
            --><li><a href="{{ h.get_parent_site_url() }}/disclaimer">{{ _('Disclaimer') }}</a></li><!--
            --><li><a href="{{ h.get_parent_site_url() }}/copyright">{{ _('Copyright') }}</a></li><!--
            --><li><a href="{{ h.get_parent_site_url() }}/accessibility">{{ _('Accessibility') }}</a></li><!--
            --><li><a href="{{ h.url_for('sitemap.index') }}">{{ _('Sitemap') }}</a></li><!--
            --><li><a href="{{ h.get_parent_site_url() }}/contact-us">{{ _('Contact us') }}</a></li><!--
          --></ul>
          <div class="rpl-links-and-copyright__copyright">© Copyright State Government of Victoria</div>
        </div>
      </div>
      <div class="rpl-site-footer__logos">
        <a href="https://vic.gov.au" target="_blank" class="rpl-link rpl-site-footer__logo">
          <img src="/images/vic-footer-logo.svg" alt="Victoria Government Website">
        </a>
      </div>
    </div>
  </div>
</footer>

ckanext/datavic_odp_theme/templates/header.html
{% block header_wrapper %}

{% block header_account %}
  {% if g.userobj %}
  <nav id="account-menu" class="account-masthead">
    <div class="container">
      {% block header_account_container_content %}
        {% if g.userobj %}
          <div class="account avatar authed" data-module="me" data-me="{{ g.userobj.id }}">
            <ul class="unstyled">
              {% block header_account_logged %}
              {% if g.userobj.sysadmin %}
                <li>
                  <a href="{{ h.url_for('admin.index') }}" title="{{ _('Sysadmin settings') }}">
                    <i class="fa fa-gavel" aria-hidden="true"></i>
                    <span class="text">{{ _('Admin') }}</span>
                  </a>
                </li>
              {% endif %}
              <li>
                <a href="{{ h.url_for('user.read', id=g.userobj.name) }}" class="image" title="{{ _('View profile') }}">
                  {{ h.gravatar((g.userobj.email_hash if g and g.userobj else ''), size=22) }}
                  <span class="username">{{ g.userobj.display_name }}</span>
                </a>
              </li>
              {% set new_activities = h.new_activities() %}
              <li class="notifications {% if new_activities > 0 %}notifications-important{% endif %}">
                {% set notifications_tooltip = ngettext('Dashboard (%(num)d new item)', 'Dashboard (%(num)d new items)', new_activities) %}
                <a href="{{ h.url_for('activity.dashboard') }}" title="{{ notifications_tooltip }}">
                  <i class="fa fa-tachometer" aria-hidden="true"></i>
                  <span class="text">{{ _('Dashboard') }}</span>
                  <span class="badge">{{ new_activities }}</span>
                </a>
              </li>
              {% block header_account_settings_link %}
                <li>
                  <a href="{{ h.url_for('user.edit', id=g.userobj.name) }}" title="{{ _('Edit settings') }}">
                    <i class="fa fa-cog" aria-hidden="true"></i>
                    <span class="text">{{ _('Settings') }}</span>
                  </a>
                </li>
              {% endblock %}
              {% block header_account_log_out_link %}
                <li>
                  <a href="{{ h.url_for('/user/_logout') }}" title="{{ _('Log out') }}">
                    <i class="fa fa-sign-out" aria-hidden="true"></i>
                    <span class="text">{{ _('Log out') }}</span>
                  </a>
                </li>
              {% endblock %}
              {% endblock %}
            </ul>
          </div>
        {% else %}
          <nav class="account not-authed">
            <ul class="unstyled">
              {% block header_account_notlogged %}
              <li>{% link_for _('Log in'), named_route='user.login' %}</li>
              {% if h.check_access('user_create') %}
                <li>{% link_for _('Register'), named_route='user.register', class_='sub' %}</li>
              {% endif %}
              {% endblock %}
            </ul>
          </nav>
        {% endif %}
      {% endblock %}
    </div>
  </nav>
  {% endif %}
{% endblock %}

<nav id="mobile-menu" class="rpl-site-header hidden" data-module="datavic-odp-header datavic-odp-breadcrumb">
  <div class="rpl-site-header__inner">
    <div class="rpl-site-header__top">
      <div class="rpl-site-header__logo-container">
        <button id="btn-mobile-menu-close" aria-expanded="true" class="rpl-site-header__btn rpl-site-header__btn--menu rpl-site-header__btn--menu-open">
            {% snippet 'snippets/svg/close.svg' %}
            <span>{{ _('Close menu') }}</span>
        </button>
      </div>
      <div class="rpl-site-header__menu-container rpl-site-header__menu-container--vertical">
        <div class="rpl-site-header__menu">
          <div data-vpos="0" data-visibledepth="0" class="rpl-menu rpl-menu--open rpl-menu--root rpl-menu--vertical">
            <div class="rpl-menu__inner">
              <div class="rpl-menu__inner_root">
                <div class="rpl-menu__column">
                  <div class="rpl-menu__header"><!----> <!----></div>
                  <ul class="rpl-menu__items rpl-menu__items--root">
                    <li class="rpl-menu__item">
                      <a href="{{ h.url_for('search') }}" class="rpl-link rpl-menu__item-link">{{ _('Data') }}</a>
                    </li>
                    <li class="rpl-menu__item">
                      <a href="{{ h.get_parent_site_url() }}/about-datavic" class="rpl-link rpl-menu__item-link">{{ _('About us') }}</a>
                    </li>
                    <li class="rpl-menu__item">
                      <a href="{{ h.get_parent_site_url() }}/contact-us" class="rpl-link rpl-menu__item-link">{{ _('Contact us') }}</a>
                    </li>
                  </ul>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div class="rpl-site-header__btn-container"><!----> <!----></div>
    </div> <!---->
  </div>
</nav>

<nav id="main-menu" class="rpl-site-header">
  <div class="rpl-site-header__inner">
    <div class="rpl-site-header__top">
      <div class="rpl-site-header__logo-container">
        <button id="btn-mobile-menu-open" aria-expanded="false" class="rpl-site-header__btn rpl-site-header__btn--menu">
            {% snippet 'snippets/svg/burger.svg' %}
            <span>{{ _('Menu') }}</span>
        </button>

        <div class="rpl-site-header__title rpl-site-header__logo-container--vic-logo-primary rpl-site-header__logo-container--vic-logo-primary--cobrand">
          <a href="https://www.vic.gov.au/" class="rpl-link" target="_blank">
            <img src="/images/vic-header-logo.png" alt="vic_logo">
          </a>
        </div>

        <div class="rpl-site-header__title cobrand">
          <a href="{{ h.get_parent_site_url() }}" class="rpl-link">
            <img src="/images/data-vic-logo-x3.png" alt="Data.Vic logo">
          </a>
        </div>
      </div>

      <div class="rpl-site-header__menu-container rpl-site-header__menu-container--horizontal">
        <div class="rpl-site-header__menu">
          <div data-vpos="0" data-visibledepth="0" class="rpl-menu rpl-menu--root rpl-menu--horizontal">
            <div class="rpl-menu__inner">
              <div class="rpl-menu__inner_root">
                <div class="rpl-menu__column">
                  <div class="rpl-menu__header">
                    <!----> <!---->
                  </div>
                  <ul class="rpl-menu__items rpl-menu__items--root">
                    <li class="rpl-menu__item">
                      <a href="{{ h.url_for('search') }}" class="rpl-link rpl-menu__item-link">{{ _('Data') }}</a>
                    </li>
                    <li class="rpl-menu__item">
                      <a href="{{ h.get_parent_site_url() }}/about-datavic" class="rpl-link rpl-menu__item-link">{{ _('About us') }}</a>
                    </li>
                    <li class="rpl-menu__item">
                      <a href="{{ h.get_parent_site_url() }}/contact-us" class="rpl-link rpl-menu__item-link">{{ _('Contact us') }}</a>
                    </li>
                  </ul>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div class="rpl-site-header__btn-container"><!----> <!---->
      </div>
    </div> <!---->
  </div>
</nav>

{% endblock %}

ckanext/datavic_odp_theme/templates/page.html
{% ckan_extends %}

{% block skip %}
  {% if h.get_gtm_container_id() %}
    {% snippet "snippets/gtm_include_noscript.html" %}
  {% endif %}
  {{ super() }}
{% endblock %}

{% block header %}
  <header>
    {{ super() }}
  </header>
{% endblock %}

{%- block content %}
  <main>
    {% if self.breadcrumb_content() | trim %}
    <div id="breadcrumbs" class="rpl-breadcrumbs" role="breadcrumbs">
        <nav aria-label="breadcrumbs">
            <ul class="rpl-breadcrumbs__items">
                <li class="rpl-breadcrumbs__item"><a href="https://www.data.vic.gov.au" class="rpl-link rpl-breadcrumbs__link">Home</a></li>
                {% block breadcrumb_content %}{% endblock %}
            </ul>
        </nav>
    </div>
    {% endif %}

    {% block maintag %}<div id="main-content" role="main">{% endblock %}
      <div id="content" class="container">
        {% block main_content %}
          {% block flash %}
            <div class="flash-messages">
              {% block flash_inner %}
                {% for message in h.get_flashed_messages() %}
                  <div class="alert fade show in {{ message.category }}">
                    {{ h.literal(message) }}
                  </div>
                {% endfor %}
              {% endblock %}
            </div>
          {% endblock %}

          {% block toolbar %}
            <div class="toolbar">
              {% block breadcrumb %}
              {% endblock %}
            </div>
          {% endblock %}

          <div class="row {% block wrapper_class %}{% endblock %}{% if self.secondary()|trim == '' %} no-nav{% endif %}">
            {% block pre_primary %}
            {% endblock %}

            {% block primary %}
              {% set span = 9 if g.blueprint in ['user', 'admin', 'activity', 'ckanext.harvest.controllers.view:ViewController'] else 12 %}
              <div class="primary span{{ span }}">
                {% block primary_content %}
                  {{ super() }}
                {% endblock %}
              </div>
            {% endblock %}

            {% block secondary %}
              {% set span = 9 if g.blueprint in ['user', 'admin', 'activity', 'ckanext.harvest.controllers.view:ViewController'] else 12 %}
              {% if span != 12 %}
                  <aside class="secondary span3">
                    {% block secondary_content %}{% endblock %}
                  </aside>
              {% endif %}
            {% endblock %}
          </div>
        {% endblock %}
      </div>
    </div>
  </main>
{% endblock -%}


{% block page_header %}
    <div class="module-content page-header">
        {% if self.content_action() | trim %}
            <div class="content_action">
                {% block content_action %}{% endblock %}
            </div>
        {% endif %}
        <ul class="nav nav-tabs">
            {% block content_primary_nav %}{% endblock %}
        </ul>
    </div>
{% endblock %}

ckanext/datavic_odp_theme/templates/recline_view.html
{% ckan_extends %}

{% block body_extras %}
    {{ super() }}
    {% asset "datavic_odp_theme/datavic_recline_patch_css" %}
{% endblock body_extras %}